**MAESTRÍA EN INTELIGENCIA ARTIFICIAL APLICADA**

**Curso: TC5053 - Ciencia y analítica de datos**

Tecnológico de Monterrey

Prof Grettel Barceló Alonso

**Semana 3**
Bases, almacenes y manipulación de datos

---

*   NOMBRE:  Adolfo Siliceo Vásquez
*   MATRÍCULA: ------------A01841467---------------------------

---

En esta actividad usarás una base de datos relacional basada en el informe de participación y la lista del top 10 de Netflix. Incluye películas y programas de televisión, así como información sobre temporadas, métricas de visualización, fechas de estreno, duración y más, organizada en las siguientes tablas:

* `movie`: Información general de las películas.

* `tv_show`: Información general de los programas de televisión.

* `season`: Datos de las temporadas asociadas a cada programa de TV.

* `view_summary`: Métricas de visualización y rendimiento de películas o temporadas.

Revisa con detalle su esquema para que comprendas cómo se relacionan las tablas anteriores.

**NOTA IMPORTANTE:** Asegúrate de responder *explícitamente* todos los cuestionamientos.

`PyMySQL` es una librería escrita en Python puro que funciona como conector (*driver*) para motores de bases de datos MySQL, permitiendo abrir conexiones, ejecutar consultas SQL y recuperar resultados directamente desde programas en Python.

In [1]:
pip install pymysql

Requirement already satisfied: pymysql in /usr/local/lib/python3.13/dist-packages (1.2.3)

`SQLAlchemy` es una librería de Python que facilita la interacción con bases de datos y permite mantener un pool de conexiones eficiente, gestionar *commits* y *rollbacks* de forma automática y asegurar que múltiples conexiones simultáneas se manejen de manera segura, incluso cuando se ejecutan consultas SQL “puras”

In [2]:
# Importa las librerías necesarias
import pymysql
import sqlalchemy as sqla
import pandas as pd

Se crea una conexión (`conn`) para luego invocar declaraciones SQL.

In [3]:
# motor+driver://usuarioBD:clave@ipHostDBMS:puerto/esquema
# pool_recycle controla el tiempo máximo de vida de una conexión en el pool (3600 segundos = 1 hora)
db = sqla.create_engine('mysql+pymysql://mnaTC5053User:mnaTC5053Pass!@20.127.169.219:3306/Netflix', pool_recycle=3600)
conn = db.connect()

Para que tus consultas sean más legibles y fáciles de mantener, puedes usar este formato multilínea con comillas triples y `sqla.text()`. Por ejemplo:

```
query = sqla.text("""
  SELECT ---
  FROM ---
  WHERE ---
""")
pd.read_sql(query, conn)
```

1.	Extrae toda la información de las películas que duran más de 5 horas.

In [4]:
query = sqla.text("""select *
from movie
where runtime > 300 """)
df = pd.read_sql(query,conn)
df

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,5793,2024-01-01,2024-01-01,b'\x00',None,日本統一シリーズ: 映画シリーズ,None,3892,Nihontouitsu Series: Film Series
1,5794,2024-01-01,2024-01-01,b'\x00',None,釣りバカ日誌: 映画シリーズ,None,2120,Free and Easy Series: Film Series
2,5874,2024-01-01,2024-01-01,b'\x01',None,None,2021-08-06,312,Navarasa: Limited Series
3,9729,2024-01-01,2024-01-01,b'\x00',None,織田同志会 織田征仁: 映画シリーズ,None,710,Seiji Oda: Film Series
4,9730,2024-01-01,2024-01-01,b'\x00',None,キングダム～首領になった男～: 映画シリーズ,None,427,Kingdom ~ The Man Who Became the Top ~: Film S...

2.	¿Cuál es el porcentaje de películas disponibles únicamente en EU en relación con el total, excluyendo los valores `NULL`? La consulta SQL debe entregar directamente el porcentaje final. No se deben devolver resultados parciales para realizar el cálculo en Python.

In [5]:
query = sqla.text("""
 select concat(round(AVG(available_globally +0) *100,2),'%') as porcentaje
 from movie
 where available_globally is not null
                  """)
df = pd.read_sql(query,conn)
df

  porcentaje
0     16.43%

3.	¿Cuáles son los idiomas o regiones originales en la tabla de películas?
* ¿Cuántos registros tienen el campo `locale` con valor `NULL`? (NULL en SQL ⇔ None en Python)

In [6]:
query = sqla.text("""
select distinct(locale)
from movie
""")
df= pd.read_sql(query,conn)
df

  locale
0   None
1     en

solo existen registros con idioma original 'en' (english) y registros con nulos

In [7]:
query = sqla.text("""
select  count(1)
from movie
where locale is null
""")
df= pd.read_sql(query,conn)
df

   count(1)
0     11255

11,255 registros con el campo locale con valores nulos

4.	Asumiendo que los valores `NULL` en `locale` corresponden a otro idioma (diferente del inglés), el título original de la película NO debería coincidir con el título principal en dichos registros.
* Determina cuántas películas tienen títulos diferentes en estos dos campos (`title` y `original_title`).
*  ¿Coinciden los resultados (cantidad de `NULL` y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes.
* Finalmente, concluye si la suposición de que los valores `NULL` en `locale` indican que la película está en otro idioma es válida.

In [8]:
titulos = sqla.text("""
    select count(*)
                    from movie
                    where locale is null
                    and original_title <> title
""")
df = pd.read_sql(titulos, conn)
df

   count(*)
0      3947

3947 peliculas tienen diferentes valores en sus campos title y original_title

*  ¿Coinciden los resultados (cantidad de `NULL` y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes.

no coinciden, debido a que son 11255 con locate = null
de los cuales:
3947 son registros con titulos diferentes.

las características de los registros restantes son:
17   son registros con titulos iguales.
7291 son registros con original_title igual a null.
 esto lo podemos comprobar con las siguientes instrucciones:

In [9]:
titulos = sqla.text("""
    select count(*)
                    from movie
                    where locale is null
                    and original_title = title
""")
df = pd.read_sql(titulos, conn)
df

   count(*)
0        17

In [10]:
titulos = sqla.text("""
    select count(*)
                    from movie
                    where locale is null
                    and original_title is null
""")
df = pd.read_sql(titulos, conn)
df

   count(*)
0      7291

* Finalmente, concluye si la suposición de que los valores `NULL` en `locale` indican que la película está en otro idioma es válida.

no es válida, debido a que hay peliculas cuyo original_title se desconoce ya que está en null y cuyo titulo está in inglés. Por ejemplo: The Super Mario Bros. Movie que debería tener locale= 'en' ya que su idioma original está en inglés y en original_title debería tener el titulo en su idioma original, sin embargo, tiene los dos campos en null

5.	Determina el título de la película que ha permanecido más tiempo en el top 10.

In [11]:
top10 = sqla.text("""
  select title,   cumulative_weeks_in_top10
  from movie  join view_summary
  on movie.id = view_summary.movie_id
  order by view_summary.cumulative_weeks_in_top10 desc
limit 1

""")
df = pd.read_sql(top10, conn)
df

           title  cumulative_weeks_in_top10
0  The Boss Baby                         22

6.	Identifica los 5 programas de TV con mayor cantidad de temporadas.

In [12]:
tv_shou = sqla.text("""
    select tv_show.title, count(*)
    from tv_show join season
    on tv_show.id = season.tv_show_id
    group by tv_show.title
    order by 2 desc
    limit 5
""")
df = pd.read_sql(tv_shou, conn)
df

                               title  count(*)
0                     Grey's Anatomy        20
1                   Naruto Shippuden        20
2                   Heartland (2007)        17
3  It's Always Sunny in Philadelphia        16
4                               NCIS        15

7.	¿Cuáles son los intervalos de fechas de los resúmenes en la tabla `view_summary` de los períodos (`duration`) semestrales?

In [13]:
intervalos = sqla.text("""

select   start_date, end_date
from view_summary
where duration = 'SEMI_ANNUALLY'
group by   start_date, end_date

""")
df = pd.read_sql(intervalos,conn)
df

   start_date    end_date
0  2024-01-01  2024-06-30
1  2023-07-01  2023-12-31

8.	Ordena las temporadas de *Grey's Anatomy* según la cantidad de vistas registradas en el primer período semestral de 2024.
* ¿Cómo interpretarías los resultados obtenidos?

In [14]:
tv_shou = sqla.text("""
# id de grey's anatomy es 347
select a.title, b.start_date, b.end_date, b.views
from season  a join view_summary b
on a.id = b.season_id
      where tv_show_id=347
      and start_date between '2024-01-01' and '2024-06-30'
      order by b.views desc;
""")
df = pd.read_sql(tv_shou, conn)
df

                        title  start_date    end_date    views
0    Grey's Anatomy: Season 1  2024-01-01  2024-06-30  3600000
1    Grey's Anatomy: Season 2  2024-01-01  2024-06-30  3100000
2    Grey's Anatomy: Season 3  2024-01-01  2024-06-30  2900000
3    Grey's Anatomy: Season 5  2024-01-01  2024-06-30  2900000
4    Grey's Anatomy: Season 4  2024-01-01  2024-06-30  2900000
5    Grey's Anatomy: Season 6  2024-01-01  2024-06-30  2800000
6    Grey's Anatomy: Season 7  2024-01-01  2024-06-30  2700000
7    Grey's Anatomy: Season 8  2024-01-01  2024-06-30  2600000
8    Grey's Anatomy: Season 9  2024-01-01  2024-06-30  2500000
9   Grey's Anatomy: Season 10  2024-01-01  2024-06-30  2400000
10  Grey's Anatomy: Season 11  2024-01-01  2024-06-30  2200000
11  Grey's Anatomy: Season 12  2024-01-01  2024-06-30  2000000
12  Grey's Anatomy: Season 13  2024-01-01  2024-06-30  2000000
13  Grey's Anatomy: Season 14  2024-01-01  2024-06-30  2000000
14  Grey's Anatomy: Season 19  2024-01-01  2024-06-30  2000000
15  Grey's Anatomy: Season 15  2024-01-01  2024-06-30  1900000
16  Grey's Anatomy: Season 16  2024-01-01  2024-06-30  1800000
17  Grey's Anatomy: Season 18  2024-01-01  2024-06-30  1700000
18  Grey's Anatomy: Season 17  2024-01-01  2024-06-30  1700000
19  Grey's Anatomy: Season 20  2024-01-01  2024-06-30   100000

se obtienen lo resultados  de los periodos de enero a junio del 2024 con lo que se cumple el requisito de ordernar las vistas del primer semestre del 2024, la primera temporada fue la que más vistas tuvo vistas.

9.	Todas las consultas anteriores podrían hacerse también con la lógica relacional implementada en Pandas, que permite replicar la mayoría de las operaciones de SQL. Si los dataframes se han llenado como sigue, resuelve la consulta 8 utilizando las funciones de Pandas.

In [15]:
tv_show = pd.read_sql(sqla.text('SELECT * FROM tv_show'), conn)
season = pd.read_sql(sqla.text('SELECT * FROM season'), conn)
view_summary = pd.read_sql(sqla.text('SELECT * FROM view_summary'), conn)

In [16]:
# id de grey's anatomy es 347
#select a.title, b.start_date, b.end_date, b.views
#from season  a join view_summary b
#on a.id = b.season_id
#      where tv_show_id=347
#      and start_date between '2024-01-01' and '2024-06-30'
#      order by b.views desc;

df = pd.merge(season, view_summary, left_on='id', right_on='season_id')
df['start_date'] = pd.to_datetime(df['start_date'])
df = df[(df['tv_show_id'] == 347) & (df['start_date'] >= '2024-01-01') & (df['start_date'] <= '2024-06-30')][['title','start_date','end_date','views']]
df.sort_values(by='views', ascending=False)

                          title start_date    end_date    views
984    Grey's Anatomy: Season 1 2024-01-01  2024-06-30  3600000
1186   Grey's Anatomy: Season 2 2024-01-01  2024-06-30  3100000
1286   Grey's Anatomy: Season 3 2024-01-01  2024-06-30  2900000
1288   Grey's Anatomy: Season 5 2024-01-01  2024-06-30  2900000
1299   Grey's Anatomy: Season 4 2024-01-01  2024-06-30  2900000
1350   Grey's Anatomy: Season 6 2024-01-01  2024-06-30  2800000
1424   Grey's Anatomy: Season 7 2024-01-01  2024-06-30  2700000
1482   Grey's Anatomy: Season 8 2024-01-01  2024-06-30  2600000
1539   Grey's Anatomy: Season 9 2024-01-01  2024-06-30  2500000
1599  Grey's Anatomy: Season 10 2024-01-01  2024-06-30  2400000
1781  Grey's Anatomy: Season 11 2024-01-01  2024-06-30  2200000
2003  Grey's Anatomy: Season 12 2024-01-01  2024-06-30  2000000
2007  Grey's Anatomy: Season 13 2024-01-01  2024-06-30  2000000
2009  Grey's Anatomy: Season 14 2024-01-01  2024-06-30  2000000
2017  Grey's Anatomy: Season 19 2024-01-01  2024-06-30  2000000
2115  Grey's Anatomy: Season 15 2024-01-01  2024-06-30  1900000
2240  Grey's Anatomy: Season 16 2024-01-01  2024-06-30  1800000
2356  Grey's Anatomy: Season 18 2024-01-01  2024-06-30  1700000
2367  Grey's Anatomy: Season 17 2024-01-01  2024-06-30  1700000
9967  Grey's Anatomy: Season 20 2024-01-01  2024-06-30   100000

`MySQL` es un sistema de gestión de bases de datos relacional, pero desde Python también es posible extraer información de bases de datos no relacionales, como `Firestore`, `MongoDB` o `Cassandra`, utilizando conectores o integraciones específicas. Esto permite combinar datos de diferentes fuentes según las necesidades del análisis o la aplicación.

En el siguiente ejercicio usarás un ejemplo con `Firestore` desde Python. Para ello utilizarás los módulos `credentials` y `firestore` de la biblioteca `firebase_admin`.

In [17]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

En `Firestore`, a diferencia de `MySQL` donde se utiliza un usuario y contraseña para conectarse, la autenticación se realiza mediante un archivo JSON que almacena las credenciales necesarias para acceder a la base de datos. Este archivo contiene las claves y la información de configuración que permiten a Python establecer la conexión de manera segura.

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [19]:
# Debes descargar el archivo de credenciales "consultancy.json" (disponible en las instrucciones de Canvas) y ubicarte en la carpeta donde lo almacenaste
import os
DIR = "/content/drive/MyDrive/Ciencia Analitica de Datos/Semana3/"
os.chdir(DIR)

In [20]:
# consultancy.json almacena la clave privada para autenticar una cuenta y autorizar el acceso a los servicios
# A través de la función Certificate(), se regresa una credencial inicializada, que puedes utilizar para crear una nueva instancia de la aplicación
cred = credentials.Certificate('consultancy.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

10.	Investiga cómo leer la colección `EMPLOYEE` y mostrar su contenido en un dataframe. Asegúrate de incluir el `id` en el resultado

In [21]:
empleados_ref = db.collection(u'EMPLOYEE')

empleados = empleados_ref.stream()

for empleado in empleados:
  print(f'{empleado.id} => {empleado.to_dict()}')

8LcLuxVHGAd2d9IQc5jF => {'emp_fname': 'David', 'emp_lname': 'Senior', 'id': '8LcLuxVHGAd2d9IQc5jF', 'emp_hiredate': DatetimeWithNanoseconds(1989, 7, 12, 6, 0, tzinfo=datetime.timezone.utc)}
Fzd60D6Z2CU4n0wVV8YN => {'emp_lname': 'Smithfield', 'emp_fname': 'William', 'id': 'Fzd60D6Z2CU4n0wVV8YN', 'emp_hiredate': DatetimeWithNanoseconds(2004, 6, 4, 5, 0, tzinfo=datetime.timezone.utc)}
lX5xuQ5w3i6ib2ExccWY => {'emp_lname': 'News', 'emp_fname': 'John', 'id': 'lX5xuQ5w3i6ib2ExccWY', 'emp_hiredate': DatetimeWithNanoseconds(2000, 11, 8, 6, 0, tzinfo=datetime.timezone.utc)}
yocFj2lichOkbAj9NBfp => {'emp_lname': 'Arbough', 'emp_fname': 'June', 'id': 'yocFj2lichOkbAj9NBfp', 'emp_hiredate': DatetimeWithNanoseconds(1996, 12, 1, 6, 0, tzinfo=datetime.timezone.utc)}

Fuente de apoyo:

Luis Felipe de Jesús Hernández Quintanar. (s.f.). Programación Avanzada: Firebase para Python [Video]. Youtube. https://www.youtube.com/watch?v=e3Tjv8oyt7A

In [22]:
 empleados = empleados_ref.stream()

datos = [empleado.to_dict() for empleado in empleados]
empleados_df = pd.DataFrame(datos)
empleados_df=empleados_df.set_index('id')
empleados_df

                     emp_fname   emp_lname              emp_hiredate
id
8LcLuxVHGAd2d9IQc5jF     David      Senior 1989-07-12 06:00:00+00:00
Fzd60D6Z2CU4n0wVV8YN   William  Smithfield 2004-06-04 05:00:00+00:00
lX5xuQ5w3i6ib2ExccWY      John        News 2000-11-08 06:00:00+00:00
yocFj2lichOkbAj9NBfp      June     Arbough 1996-12-01 06:00:00+00:00

Para este ultimo ejercicio se hizo uso de IA

Anthropic. (2026). Claude (Opus 5) [Modelo de lenguaje grande], **busqueda de fuentes bibliográficas / depuración / tutoria**. https://claude.ai/

In [23]:
firebase_admin.delete_app(firebase_admin.get_app())

---

**Declaración de uso de IA**

Si aplica, deberá indicarse la herramienta y el modelo empleado en la entrega, así como la finalidad de su uso (generación de código / depuración / optimización).

Por ejemplo:

*   OpenAI. (2026). *ChatGPT (basado en GPT-4)* [Modelo de lenguaje grande], utilizado para generación de código y depuración. https://chat.openai.com/

---